export const users = [
  { name: 'John Doe', email: 'john.doe@example.com', password: 'password123' },
  { name: 'Jane Smith', email: 'jane.smith@example.com', password: 'securepass456' },
  { name: 'Alice Johnson', email: 'alice.johnson@example.com', password: 'mysecretpass' },
  { name: 'Michael Brown', email: 'michael.brown@example.com', password: 'passw0rd' },
  { name: 'Emily Davis', email: 'emily.davis@example.com', password: 'strongpass' },
  { name: 'David Wilson', email: 'david.wilson@example.com', password: 'mypassword' },
  { name: 'Sophia Martinez', email: 'sophia.martinez@example.com', password: 'safepass789' },
  { name: 'James Taylor', email: 'james.taylor@example.com', password: 'topsecret' },
  { name: 'Olivia Anderson', email: 'olivia.anderson@example.com', password: 'hiddenpass' },
  { name: 'Lucas Thomas', email: 'lucas.thomas@example.com', password: 'letmein123' },
  { name: 'Benjamin Clark', email: 'benjamin.clark@example.com', password: 'benpass123' },
  { name: 'Natalie Walker', email: 'natalie.walker@example.com', password: 'natsecure45' },
  { name: 'Ethan Harris', email: 'ethan.harris@example.com', password: 'ethanpass99' },
  { name: 'Grace Lewis', email: 'grace.lewis@example.com', password: 'graceful123' },
  { name: 'Noah Hall', email: 'noah.hall@example.com', password: 'noahpass67' },
  { name: 'Mia Adams', email: 'mia.adams@example.com', password: 'miapass89' },
  { name: 'Liam Allen', email: 'liam.allen@example.com', password: 'liamsecure' },
  { name: 'Chloe King', email: 'chloe.king@example.com', password: 'chloekey123' },
  { name: 'Jacob Wright', email: 'jacob.wright@example.com', password: 'wrightpass77' },
  { name: 'Ella Scott', email: 'ella.scott@example.com', password: 'ellasecure12' },
  { name: 'Daniel Perez', email: 'daniel.perez@example.com', password: 'danpass432' },
  { name: 'Victoria Campbell', email: 'victoria.campbell@example.com', password: 'vicsecure12' },
  { name: 'Elijah Mitchell', email: 'elijah.mitchell@example.com', password: 'elipass998' },
  { name: 'Zoe Roberts', email: 'zoe.roberts@example.com', password: 'zoepass007' },
  { name: 'Alexander Carter', email: 'alex.carter@example.com', password: 'alexpass02' },
  { name: 'Isabella Turner', email: 'isabella.turner@example.com', password: 'turnpass12' },
  { name: 'Matthew Phillips', email: 'matthew.phillips@example.com', password: 'mattpass89' },
  { name: 'Sophia Evans', email: 'sophia.evans@example.com', password: 'sofevan45' },
  { name: 'Ryan Rivera', email: 'ryan.rivera@example.com', password: 'ryanpass78' },
  { name: 'Abigail White', email: 'abigail.white@example.com', password: 'abipass34' },
  { name: 'Nathan Rodriguez', email: 'nathan.rodriguez@example.com', password: 'nathrod999' },
  { name: 'Hannah Martinez', email: 'hannah.martinez@example.com', password: 'hansecure88' },
  { name: 'Ethan Moore', email: 'ethan.moore@example.com', password: 'mooreethan123' },
  { name: 'Samantha Gonzalez', email: 'samantha.gonzalez@example.com', password: 'sampass234' },
  { name: 'Joshua Ward', email: 'joshua.ward@example.com', password: 'joshsecure' },
  { name: 'Ava Howard', email: 'ava.howard@example.com', password: 'avapass09' },
  { name: 'Andrew Torres', email: 'andrew.torres@example.com', password: 'torrand99' },
  { name: 'Elizabeth Ramirez', email: 'elizabeth.ramirez@example.com', password: 'elizpass76' },
  { name: 'Christopher Bailey', email: 'christopher.bailey@example.com', password: 'chrispass45' },
  { name: 'Madison Cooper', email: 'madison.cooper@example.com', password: 'madpass123' },
];


export const families = [
  { family_name: 'Smith Family' },
  { family_name: 'Johnson Family' },
  { family_name: 'Brown Family' },
  { family_name: 'Davis Family' },
  { family_name: 'Wilson Family' },
  { family_name: 'Martinez Family' },
  { family_name: 'Taylor Family' },
  { family_name: 'Anderson Family' },
  { family_name: 'Thomas Family' },
  { family_name: 'Clark Family' },
  { family_name: 'Walker Family' },
  { family_name: 'Harris Family' },
  { family_name: 'Lewis Family' },
  { family_name: 'Hall Family' },
  { family_name: 'Adams Family' },
  { family_name: 'Allen Family' },
  { family_name: 'King Family' },
  { family_name: 'Wright Family' },
  { family_name: 'Scott Family' },
  { family_name: 'Perez Family' },
  { family_name: 'Campbell Family' },
  { family_name: 'Mitchell Family' },
  { family_name: 'Roberts Family' },
  { family_name: 'Carter Family' },
  { family_name: 'Turner Family' },
  { family_name: 'Phillips Family' },
  { family_name: 'Evans Family' },
  { family_name: 'Rivera Family' },
  { family_name: 'White Family' },
  { family_name: 'Rodriguez Family' },
  { family_name: 'Gonzalez Family' },
  { family_name: 'Moore Family' },
  { family_name: 'Howard Family' },
  { family_name: 'Torres Family' },
  { family_name: 'Ramirez Family' },
  { family_name: 'Bailey Family' },
  { family_name: 'Cooper Family' },
  { family_name: 'Reed Family' },
  { family_name: 'Young Family' },
  { family_name: 'Baker Family' },
];


export const family_users = [
  { user_id: 1, family_id: 1 }, // John Doe belongs to Smith Family
  { user_id: 2, family_id: 1 }, // Jane Smith also belongs to Smith Family
  { user_id: 2, family_id: 2 }, // Jane Smith also belongs to Johnson Family
  { user_id: 3, family_id: 2 }, // Alice Johnson belongs to Johnson Family
  { user_id: 4, family_id: 3 }, // Michael Brown belongs to Brown Family
  { user_id: 5, family_id: 4 }, // Emily Davis belongs to Davis Family
  { user_id: 6, family_id: 5 }, // David Wilson belongs to Wilson Family
  { user_id: 7, family_id: 6 }, // Sophia Martinez belongs to Martinez Family
  { user_id: 8, family_id: 7 }, // James Taylor belongs to Taylor Family
  { user_id: 9, family_id: 8 }, // Olivia Anderson belongs to Anderson Family
  { user_id: 10, family_id: 9 }, // Lucas Thomas belongs to Thomas Family
  { user_id: 11, family_id: 10 }, // Benjamin Clark belongs to Clark Family
  { user_id: 12, family_id: 11 }, // Natalie Walker belongs to Walker Family
  { user_id: 13, family_id: 12 }, // Ethan Harris belongs to Harris Family
  { user_id: 14, family_id: 13 }, // Grace Lewis belongs to Lewis Family
  { user_id: 15, family_id: 14 }, // Noah Hall belongs to Hall Family
  { user_id: 16, family_id: 15 }, // Mia Adams belongs to Adams Family
  { user_id: 17, family_id: 16 }, // Liam Allen belongs to Allen Family
  { user_id: 18, family_id: 17 }, // Chloe King belongs to King Family
  { user_id: 19, family_id: 18 }, // Jacob Wright belongs to Wright Family
  { user_id: 20, family_id: 19 }, // Ella Scott belongs to Scott Family
  { user_id: 21, family_id: 20 }, // Daniel Perez belongs to Perez Family
  { user_id: 22, family_id: 21 }, // Victoria Campbell belongs to Campbell Family
  { user_id: 23, family_id: 22 }, // Elijah Mitchell belongs to Mitchell Family
  { user_id: 24, family_id: 23 }, // Zoe Roberts belongs to Roberts Family
  { user_id: 25, family_id: 24 }, // Alexander Carter belongs to Carter Family
  { user_id: 26, family_id: 25 }, // Isabella Turner belongs to Turner Family
  { user_id: 27, family_id: 26 }, // Matthew Phillips belongs to Phillips Family
  { user_id: 28, family_id: 27 }, // Sophia Evans belongs to Evans Family
  { user_id: 29, family_id: 28 }, // Ryan Rivera belongs to Rivera Family
  { user_id: 30, family_id: 29 }, // Abigail White belongs to White Family
  { user_id: 31, family_id: 30 }, // Nathan Rodriguez belongs to Rodriguez Family
  { user_id: 32, family_id: 31 }, // Hannah Martinez belongs to Gonzalez Family
  { user_id: 33, family_id: 32 }, // Ethan Moore belongs to Moore Family
  { user_id: 34, family_id: 33 }, // Samantha Gonzalez belongs to Gonzalez Family
  { user_id: 35, family_id: 34 }, // Joshua Ward belongs to Howard Family
  { user_id: 36, family_id: 35 }, // Ava Howard belongs to Howard Family
  { user_id: 37, family_id: 36 }, // Andrew Torres belongs to Torres Family
  { user_id: 38, family_id: 37 }, // Elizabeth Ramirez belongs to Ramirez Family
  { user_id: 39, family_id: 38 }, // Christopher Bailey belongs to Bailey Family
  { user_id: 40, family_id: 39 }, // Madison Cooper belongs to Cooper Family
];


export const recipes = [
  { recipe_name: 'Spaghetti Bolognese', recipe_servings: 4, recipe_description: 'A classic Italian pasta dish.', recipe_instructions: ['Step 1: Cook pasta', 'Step 2: Prepare sauce', 'Step 3: Combine and serve'], meal_type: 'Dinner', recipe_image: 'spaghetti.jpg', created_on: new Date(), user_id: 1 },
  { recipe_name: 'Chicken Alfredo', recipe_servings: 4, recipe_description: 'A creamy and rich pasta dish with chicken.', recipe_instructions: ['Step 1: Cook pasta', 'Step 2: Prepare chicken', 'Step 3: Make Alfredo sauce', 'Step 4: Combine and serve'], meal_type: 'Dinner', recipe_image: 'chicken_alfredo.jpg', created_on: new Date(), user_id: 2 },
  { recipe_name: 'Vegan Tacos', recipe_servings: 4, recipe_description: 'A plant-based taco filled with fresh veggies and beans.', recipe_instructions: ['Step 1: Prepare vegetables', 'Step 2: Cook beans', 'Step 3: Assemble tacos'], meal_type: 'Dinner', recipe_image: 'vegan_tacos.jpg', created_on: new Date(), user_id: 3 },
  { recipe_name: 'Beef Stew', recipe_servings: 6, recipe_description: 'A hearty stew with tender beef and vegetables.', recipe_instructions: ['Step 1: Brown beef', 'Step 2: Add vegetables', 'Step 3: Simmer and serve'], meal_type: 'Dinner', recipe_image: 'beef_stew.jpg', created_on: new Date(), user_id: 4 },
  { recipe_name: 'Salmon with Lemon', recipe_servings: 4, recipe_description: 'Grilled salmon with a fresh lemon glaze.', recipe_instructions: ['Step 1: Grill salmon', 'Step 2: Prepare lemon glaze', 'Step 3: Serve with a side of vegetables'], meal_type: 'Dinner', recipe_image: 'salmon_lemon.jpg', created_on: new Date(), user_id: 5 },
  { recipe_name: 'Pancakes', recipe_servings: 4, recipe_description: 'Fluffy pancakes served with syrup.', recipe_instructions: ['Step 1: Mix ingredients', 'Step 2: Cook pancakes', 'Step 3: Serve with syrup'], meal_type: 'Breakfast', recipe_image: 'pancakes.jpg', created_on: new Date(), user_id: 6 },
  { recipe_name: 'Caesar Salad', recipe_servings: 2, recipe_description: 'A fresh salad with romaine lettuce, croutons, and Caesar dressing.', recipe_instructions: ['Step 1: Toss lettuce', 'Step 2: Add croutons and dressing', 'Step 3: Serve'], meal_type: 'Lunch', recipe_image: 'caesar_salad.jpg', created_on: new Date(), user_id: 7 },
  { recipe_name: 'Vegetable Stir Fry', recipe_servings: 4, recipe_description: 'A quick stir-fry with mixed vegetables.', recipe_instructions: ['Step 1: Stir-fry vegetables', 'Step 2: Add soy sauce', 'Step 3: Serve with rice'], meal_type: 'Dinner', recipe_image: 'vegetable_stir_fry.jpg', created_on: new Date(), user_id: 8 },
  { recipe_name: 'Pizza Margherita', recipe_servings: 2, recipe_description: 'A simple pizza with tomato, mozzarella, and basil.', recipe_instructions: ['Step 1: Prepare dough', 'Step 2: Add toppings', 'Step 3: Bake and serve'], meal_type: 'Dinner', recipe_image: 'pizza_margherita.jpg', created_on: new Date(), user_id: 9 },
  { recipe_name: 'Chicken Curry', recipe_servings: 4, recipe_description: 'A spicy curry made with chicken and aromatic spices.', recipe_instructions: ['Step 1: Cook chicken', 'Step 2: Prepare curry sauce', 'Step 3: Combine and serve with rice'], meal_type: 'Dinner', recipe_image: 'chicken_curry.jpg', created_on: new Date(), user_id: 10 },
  { recipe_name: 'Beef Tacos', recipe_servings: 4, recipe_description: 'Tacos filled with seasoned ground beef and toppings.', recipe_instructions: ['Step 1: Cook ground beef', 'Step 2: Prepare taco toppings', 'Step 3: Assemble tacos'], meal_type: 'Dinner', recipe_image: 'beef_tacos.jpg', created_on: new Date(), user_id: 11 },
  { recipe_name: 'Apple Pie', recipe_servings: 8, recipe_description: 'A classic dessert made with apples and a flaky crust.', recipe_instructions: ['Step 1: Prepare filling', 'Step 2: Assemble pie', 'Step 3: Bake and serve'], meal_type: 'Dessert', recipe_image: 'apple_pie.jpg', created_on: new Date(), user_id: 12 },
  { recipe_name: 'Grilled Cheese Sandwich', recipe_servings: 2, recipe_description: 'A crispy grilled sandwich with melted cheese.', recipe_instructions: ['Step 1: Prepare bread and cheese', 'Step 2: Grill sandwich', 'Step 3: Serve'], meal_type: 'Lunch', recipe_image: 'grilled_cheese.jpg', created_on: new Date(), user_id: 13 },
  { recipe_name: 'Lasagna', recipe_servings: 6, recipe_description: 'A layered pasta dish with ground beef and ricotta cheese.', recipe_instructions: ['Step 1: Prepare meat sauce', 'Step 2: Layer pasta and cheese', 'Step 3: Bake and serve'], meal_type: 'Dinner', recipe_image: 'lasagna.jpg', created_on: new Date(), user_id: 14 },
  { recipe_name: 'Chicken Parmesan', recipe_servings: 4, recipe_description: 'Breaded chicken topped with marinara sauce and cheese.', recipe_instructions: ['Step 1: Bread chicken', 'Step 2: Fry and top with sauce', 'Step 3: Bake and serve'], meal_type: 'Dinner', recipe_image: 'chicken_parmesan.jpg', created_on: new Date(), user_id: 15 },
  { recipe_name: 'Baked Ziti', recipe_servings: 6, recipe_description: 'A baked pasta dish with marinara sauce and mozzarella.', recipe_instructions: ['Step 1: Prepare pasta', 'Step 2: Add sauce and cheese', 'Step 3: Bake and serve'], meal_type: 'Dinner', recipe_image: 'baked_ziti.jpg', created_on: new Date(), user_id: 16 },
  { recipe_name: 'Pork Chops', recipe_servings: 4, recipe_description: 'Grilled pork chops with a sweet glaze.', recipe_instructions: ['Step 1: Grill pork chops', 'Step 2: Prepare glaze', 'Step 3: Serve'], meal_type: 'Dinner', recipe_image: 'pork_chops.jpg', created_on: new Date(), user_id: 17 },
  { recipe_name: 'Shrimp Scampi', recipe_servings: 4, recipe_description: 'Shrimp cooked in garlic butter sauce.', recipe_instructions: ['Step 1: Cook shrimp', 'Step 2: Prepare garlic butter', 'Step 3: Serve with pasta'], meal_type: 'Dinner', recipe_image: 'shrimp_scampi.jpg', created_on: new Date(), user_id: 18 },
  { recipe_name: 'Egg Salad', recipe_servings: 2, recipe_description: 'A creamy egg salad with mayo and mustard.', recipe_instructions: ['Step 1: Boil eggs', 'Step 2: Prepare salad dressing', 'Step 3: Mix and serve'], meal_type: 'Lunch', recipe_image: 'egg_salad.jpg', created_on: new Date(), user_id: 19 },
  { recipe_name: 'Fruit Salad', recipe_servings: 4, recipe_description: 'A refreshing salad made with mixed fruits.', recipe_instructions: ['Step 1: Prepare fruit', 'Step 2: Toss together', 'Step 3: Serve'], meal_type: 'Snack', recipe_image: 'fruit_salad.jpg', created_on: new Date(), user_id: 20 },
  { recipe_name: 'Chocolate Cake', recipe_servings: 8, recipe_description: 'A moist chocolate cake with a rich frosting.', recipe_instructions: ['Step 1: Prepare batter', 'Step 2: Bake cake', 'Step 3: Frost and serve'], meal_type: 'Dessert', recipe_image: 'chocolate_cake.jpg', created_on: new Date(), user_id: 21 },
  { recipe_name: 'Beef Burritos', recipe_servings: 4, recipe_description: 'Burritos filled with seasoned beef and cheese.', recipe_instructions: ['Step 1: Cook beef', 'Step 2: Prepare burrito fillings', 'Step 3: Assemble and serve'], meal_type: 'Dinner', recipe_image: 'beef_burritos.jpg', created_on: new Date(), user_id: 22 },
  { recipe_name: 'Vegetable Soup', recipe_servings: 6, recipe_description: 'A comforting soup made with a variety of vegetables.', recipe_instructions: ['Step 1: Prepare vegetables', 'Step 2: Simmer soup', 'Step 3: Serve'], meal_type: 'Dinner', recipe_image: 'vegetable_soup.jpg', created_on: new Date(), user_id: 23 },
  { recipe_name: 'Eggplant Parmesan', recipe_servings: 4, recipe_description: 'Breaded eggplant topped with marinara sauce and mozzarella.', recipe_instructions: ['Step 1: Bread eggplant', 'Step 2: Fry and top with sauce', 'Step 3: Bake and serve'], meal_type: 'Dinner', recipe_image: 'eggplant_parmesan.jpg', created_on: new Date(), user_id: 24 },
];


export const tags = [
  { tag_name: 'Vegan' },
  { tag_name: 'Gluten-Free' },
  { tag_name: 'Low Carb' },
  { tag_name: 'Dairy-Free' },
  { tag_name: 'High Protein' },
  { tag_name: 'Vegetarian' },
  { tag_name: 'Paleo' },
  { tag_name: 'Keto' },
  { tag_name: 'Whole30' },
  { tag_name: 'Sugar-Free' },
  { tag_name: 'Nut-Free' },
  { tag_name: 'Soy-Free' },
  { tag_name: 'Halal' },
  { tag_name: 'Kosher' },
  { tag_name: 'Organic' },
  { tag_name: 'Easy' },
  { tag_name: 'Quick' },
  { tag_name: 'Family-Friendly' },
  { tag_name: 'Kid-Friendly' },
  { tag_name: 'Spicy' },
  { tag_name: 'Comfort Food' },
  { tag_name: 'Seasonal' },
  { tag_name: 'Meal Prep' },
  { tag_name: 'One-Pot' },
  { tag_name: 'Gluten-Free Flour' },
  { tag_name: 'Crockpot' },
  { tag_name: 'Air Fryer' },
  { tag_name: 'Fried' },
  { tag_name: 'Baked' },
  { tag_name: 'Raw' },
  { tag_name: 'Breakfast' },
  { tag_name: 'Lunch' },
  { tag_name: 'Dinner' },
  { tag_name: 'Dessert' },
  { tag_name: 'Snacks' },
  { tag_name: 'Side Dish' },
  { tag_name: 'Holiday' },
  { tag_name: 'Summer' },
  { tag_name: 'Fall' },
  { tag_name: 'Winter' },
];


export const recipeTags = [
  { recipe_id: 1, tag_id: 1 },
  { recipe_id: 1, tag_id: 2 },
  { recipe_id: 1, tag_id: 3 },
  { recipe_id: 2, tag_id: 4 },
  { recipe_id: 2, tag_id: 5 },
  { recipe_id: 3, tag_id: 6 },
  { recipe_id: 3, tag_id: 7 },
  { recipe_id: 4, tag_id: 8 },
  { recipe_id: 4, tag_id: 9 },
  { recipe_id: 5, tag_id: 10 },
  { recipe_id: 5, tag_id: 11 },
  { recipe_id: 6, tag_id: 12 },
  { recipe_id: 6, tag_id: 13 },
  { recipe_id: 7, tag_id: 14 },
  { recipe_id: 7, tag_id: 15 },
  { recipe_id: 8, tag_id: 16 },
  { recipe_id: 8, tag_id: 17 },
  { recipe_id: 9, tag_id: 18 },
  { recipe_id: 9, tag_id: 19 },
  { recipe_id: 10, tag_id: 20 },
  { recipe_id: 10, tag_id: 21 },
  { recipe_id: 11, tag_id: 22 },
  { recipe_id: 11, tag_id: 23 },
  { recipe_id: 12, tag_id: 24 },
  { recipe_id: 12, tag_id: 25 },
  { recipe_id: 13, tag_id: 26 },
  { recipe_id: 13, tag_id: 27 },
  { recipe_id: 14, tag_id: 28 },
  { recipe_id: 14, tag_id: 29 },
  { recipe_id: 15, tag_id: 30 },
  { recipe_id: 15, tag_id: 31 },
  { recipe_id: 16, tag_id: 32 },
  { recipe_id: 16, tag_id: 33 },
  { recipe_id: 17, tag_id: 34 },
  { recipe_id: 17, tag_id: 35 },
  { recipe_id: 18, tag_id: 36 },
  { recipe_id: 18, tag_id: 37 },
  { recipe_id: 19, tag_id: 38 },
  { recipe_id: 19, tag_id: 39 },
  { recipe_id: 20, tag_id: 40 },
];


export const ingredients = [
  { ingredient_name: 'Tomato' },
  { ingredient_name: 'Garlic' },
  { ingredient_name: 'Olive Oil' },
  { ingredient_name: 'Onion' },
  { ingredient_name: 'Basil' },
  { ingredient_name: 'Carrot' },
  { ingredient_name: 'Celery' },
  { ingredient_name: 'Ground Beef' },
  { ingredient_name: 'Chicken Breast' },
  { ingredient_name: 'Lemon' },
  { ingredient_name: 'Spinach' },
  { ingredient_name: 'Zucchini' },
  { ingredient_name: 'Eggplant' },
  { ingredient_name: 'Bell Pepper' },
  { ingredient_name: 'Mushrooms' },
  { ingredient_name: 'Cucumber' },
  { ingredient_name: 'Cheddar Cheese' },
  { ingredient_name: 'Parmesan Cheese' },
  { ingredient_name: 'Feta Cheese' },
  { ingredient_name: 'Cottage Cheese' },
  { ingredient_name: 'Yogurt' },
  { ingredient_name: 'Tortilla' },
  { ingredient_name: 'Chicken Broth' },
  { ingredient_name: 'Tomato Paste' },
  { ingredient_name: 'Canned Tomatoes' },
  { ingredient_name: 'Pasta' },
  { ingredient_name: 'Rice' },
  { ingredient_name: 'Quinoa' },
  { ingredient_name: 'Coconut Milk' },
  { ingredient_name: 'Almonds' },
  { ingredient_name: 'Chia Seeds' },
  { ingredient_name: 'Oats' },
  { ingredient_name: 'Honey' },
  { ingredient_name: 'Maple Syrup' },
  { ingredient_name: 'Vanilla Extract' },
  { ingredient_name: 'Cinnamon' },
  { ingredient_name: 'Nutmeg' },
  { ingredient_name: 'Baking Powder' },
  { ingredient_name: 'Salt' },
  { ingredient_name: 'Pepper' },
  { ingredient_name: 'Cilantro' },
  { ingredient_name: 'Parsley' },
];


export const recipeIngredients = [
  { recipe_id: 1, ingredient_id: 1, quantity: 2, unit: 'Tomatoes', preparation_method: 'chopped' },
  { recipe_id: 1, ingredient_id: 2, quantity: 3, unit: 'cloves', preparation_method: 'minced' },
  { recipe_id: 1, ingredient_id: 3, quantity: 1, unit: 'tablespoon', preparation_method: 'cold-pressed' },
  { recipe_id: 2, ingredient_id: 4, quantity: 1, unit: 'Onion', preparation_method: 'diced' },
  { recipe_id: 2, ingredient_id: 5, quantity: 1, unit: 'cup', preparation_method: 'fresh' },
  { recipe_id: 2, ingredient_id: 6, quantity: 2, unit: 'carrots', preparation_method: 'sliced' },
  { recipe_id: 3, ingredient_id: 7, quantity: 2, unit: 'chicken breasts', preparation_method: 'diced' },
  { recipe_id: 3, ingredient_id: 8, quantity: 1, unit: 'tablespoon', preparation_method: 'minced' },
  { recipe_id: 3, ingredient_id: 9, quantity: 1, unit: 'lemon', preparation_method: 'sliced' },
  { recipe_id: 4, ingredient_id: 10, quantity: 3, unit: 'zucchini', preparation_method: 'chopped' },
  { recipe_id: 4, ingredient_id: 11, quantity: 1, unit: 'eggplant', preparation_method: 'diced' },
  { recipe_id: 4, ingredient_id: 12, quantity: 1, unit: 'bell pepper', preparation_method: 'sliced' },
  { recipe_id: 5, ingredient_id: 13, quantity: 1, unit: 'cup', preparation_method: 'sliced' },
  { recipe_id: 5, ingredient_id: 14, quantity: 1, unit: 'cup', preparation_method: 'sliced' },
  { recipe_id: 5, ingredient_id: 15, quantity: 2, unit: 'cups', preparation_method: 'shredded' },
  { recipe_id: 6, ingredient_id: 16, quantity: 1, unit: 'cup', preparation_method: 'crumbled' },
  { recipe_id: 6, ingredient_id: 17, quantity: 1, unit: 'cup', preparation_method: 'crumbled' },
  { recipe_id: 7, ingredient_id: 18, quantity: 2, unit: 'cups', preparation_method: 'plain' },
  { recipe_id: 7, ingredient_id: 19, quantity: 1, unit: 'cup', preparation_method: 'chopped' },
  { recipe_id: 8, ingredient_id: 20, quantity: 1, unit: 'tablespoon', preparation_method: 'finely chopped' },
  { recipe_id: 8, ingredient_id: 21, quantity: 1, unit: 'cup', preparation_method: 'sliced' },
  { recipe_id: 9, ingredient_id: 22, quantity: 1, unit: 'tablespoon', preparation_method: 'chopped' },
  { recipe_id: 9, ingredient_id: 23, quantity: 1, unit: 'can', preparation_method: 'crushed' },
  { recipe_id: 10, ingredient_id: 24, quantity: 1, unit: 'cup', preparation_method: 'boiled' },
  { recipe_id: 10, ingredient_id: 25, quantity: 1, unit: 'cup', preparation_method: 'steamed' },
  { recipe_id: 11, ingredient_id: 26, quantity: 1, unit: 'cup', preparation_method: 'raw' },
  { recipe_id: 11, ingredient_id: 27, quantity: 1, unit: 'cup', preparation_method: 'raw' },
  { recipe_id: 12, ingredient_id: 28, quantity: 2, unit: 'cups', preparation_method: 'baked' },
  { recipe_id: 12, ingredient_id: 29, quantity: 1, unit: 'tablespoon', preparation_method: 'blended' },
  { recipe_id: 13, ingredient_id: 30, quantity: 1, unit: 'cup', preparation_method: 'mixed' },
  { recipe_id: 13, ingredient_id: 31, quantity: 2, unit: 'tablespoons', preparation_method: 'whisked' },
  { recipe_id: 14, ingredient_id: 32, quantity: 1, unit: 'cup', preparation_method: 'roasted' },
  { recipe_id: 14, ingredient_id: 33, quantity: 1, unit: 'cup', preparation_method: 'steamed' },
  { recipe_id: 15, ingredient_id: 34, quantity: 1, unit: 'cup', preparation_method: 'soaked' },
  { recipe_id: 15, ingredient_id: 35, quantity: 1, unit: 'tablespoon', preparation_method: 'dried' },
  { recipe_id: 16, ingredient_id: 36, quantity: 1, unit: 'teaspoon', preparation_method: 'sliced' },
  { recipe_id: 16, ingredient_id: 37, quantity: 1, unit: 'teaspoon', preparation_method: 'finely chopped' },
  { recipe_id: 17, ingredient_id: 38, quantity: 1, unit: 'cup', preparation_method: 'sliced' },
  { recipe_id: 17, ingredient_id: 39, quantity: 1, unit: 'cup', preparation_method: 'finely chopped' },
  { recipe_id: 18, ingredient_id: 40, quantity: 1, unit: 'teaspoon', preparation_method: 'chopped' },
];


export const historicalNotes = [
  { note: 'This recipe was updated to be vegan in 2024.', user_id: 1, recipe_id: 1 },
  { note: 'Originally, this recipe used dairy, but now it is dairy-free.', user_id: 1, recipe_id: 1 },
  { note: 'Changed to include more vegetables in 2023.', user_id: 2, recipe_id: 2 },
  { note: 'This recipe was modified to reduce sugar content in 2022.', user_id: 3, recipe_id: 3 },
  { note: 'Added a gluten-free alternative in 2021.', user_id: 1, recipe_id: 4 },
  { note: 'Updated in 2024 to include more plant-based options.', user_id: 4, recipe_id: 5 },
  { note: 'Adjusted the serving sizes for a family-friendly version in 2024.', user_id: 5, recipe_id: 6 },
  { note: 'New version with lower sodium content, added in 2023.', user_id: 1, recipe_id: 7 },
  { note: 'Recipe modified to be lactose-free in 2023.', user_id: 2, recipe_id: 8 },
  { note: 'Updated with fresh herbs instead of dried in 2024.', user_id: 3, recipe_id: 9 },
  { note: 'Vegetarian alternative added in 2023.', user_id: 4, recipe_id: 10 },
  { note: 'Revised the cooking instructions for a quicker preparation in 2024.', user_id: 5, recipe_id: 11 },
  { note: 'Removed gluten ingredients in 2024 to accommodate dietary restrictions.', user_id: 1, recipe_id: 12 },
  { note: 'Introduced a new garnish in 2024.', user_id: 2, recipe_id: 13 },
  { note: 'Simplified the recipe in 2023 for easier cooking.', user_id: 3, recipe_id: 14 },
  { note: 'Modified to include a nut-free version in 2024.', user_id: 4, recipe_id: 15 },
  { note: 'Added spicy variant to the recipe in 2023.', user_id: 5, recipe_id: 16 },
  { note: 'Replaced high-fat ingredients with healthier options in 2024.', user_id: 1, recipe_id: 17 },
  { note: 'Updated recipe to include more protein-rich ingredients in 2024.', user_id: 2, recipe_id: 18 },
  { note: 'Introduced a new preparation method in 2023 for better flavor.', user_id: 3, recipe_id: 19 },
  { note: 'Revised for a more family-friendly recipe in 2024.', user_id: 4, recipe_id: 20 },
  { note: 'Increased serving size to cater to larger families in 2023.', user_id: 5, recipe_id: 21 },
  { note: 'Recipe adapted to be more budget-friendly in 2024.', user_id: 1, recipe_id: 22 },
  { note: 'Modified cooking time for quicker results in 2023.', user_id: 2, recipe_id: 23 },
  { note: 'Recipe altered to include fewer processed ingredients in 2024.', user_id: 3, recipe_id: 24 },
  { note: 'Changed to use organic ingredients in 2023.', user_id: 4, recipe_id: 25 },
  { note: 'Improved with a new flavor combination in 2024.', user_id: 5, recipe_id: 26 },
  { note: 'Adjusted for lower carbohydrate content in 2023.', user_id: 1, recipe_id: 27 },
  { note: 'Replaced animal products with plant-based options in 2024.', user_id: 2, recipe_id: 28 },
  { note: 'Recipe now includes a customizable sauce in 2024.', user_id: 3, recipe_id: 29 },
  { note: 'Updated for simplicity and faster preparation in 2023.', user_id: 4, recipe_id: 30 },
  { note: 'Increased vegetable content in 2024 for a healthier version.', user_id: 5, recipe_id: 31 },
  { note: 'Recipe now includes a new vegan cheese option in 2024.', user_id: 1, recipe_id: 32 },
  { note: 'Adjusted for a more savory flavor profile in 2023.', user_id: 2, recipe_id: 33 },
  { note: 'Modified to include fewer calories in 2024.', user_id: 3, recipe_id: 34 },
  { note: 'Revised recipe to enhance texture in 2023.', user_id: 4, recipe_id: 35 },
  { note: 'Adapted to use seasonal ingredients in 2024.', user_id: 5, recipe_id: 36 },
  { note: 'Reduced sugar and salt in 2023 for a healthier version.', user_id: 1, recipe_id: 37 },
  { note: 'New cooking method introduced in 2024 for better results.', user_id: 2, recipe_id: 38 },
  { note: 'Updated to be more family-friendly in 2024.', user_id: 3, recipe_id: 39 },
  { note: 'Revised for a quicker preparation time in 2023.', user_id: 4, recipe_id: 40 },
];


export const mealPlans = [
  { date: '2025-01-21', user_id: 1 },
  { date: '2025-01-22', user_id: 2 },
  { date: '2025-01-23', user_id: 3 },
  { date: '2025-01-24', user_id: 4 },
  { date: '2025-01-25', user_id: 5 },
  { date: '2025-01-26', user_id: 1 },
  { date: '2025-01-27', user_id: 2 },
  { date: '2025-01-28', user_id: 3 },
  { date: '2025-01-29', user_id: 4 },
  { date: '2025-01-30', user_id: 5 },
  { date: '2025-02-01', user_id: 1 },
  { date: '2025-02-02', user_id: 2 },
  { date: '2025-02-03', user_id: 3 },
  { date: '2025-02-04', user_id: 4 },
  { date: '2025-02-05', user_id: 5 },
  { date: '2025-02-06', user_id: 1 },
  { date: '2025-02-07', user_id: 2 },
  { date: '2025-02-08', user_id: 3 },
  { date: '2025-02-09', user_id: 4 },
  { date: '2025-02-10', user_id: 5 },
  { date: '2025-02-11', user_id: 1 },
  { date: '2025-02-12', user_id: 2 },
  { date: '2025-02-13', user_id: 3 },
  { date: '2025-02-14', user_id: 4 },
  { date: '2025-02-15', user_id: 5 },
  { date: '2025-02-16', user_id: 1 },
  { date: '2025-02-17', user_id: 2 },
  { date: '2025-02-18', user_id: 3 },
  { date: '2025-02-19', user_id: 4 },
  { date: '2025-02-20', user_id: 5 },
  { date: '2025-02-21', user_id: 1 },
  { date: '2025-02-22', user_id: 2 },
  { date: '2025-02-23', user_id: 3 },
  { date: '2025-02-24', user_id: 4 },
  { date: '2025-02-25', user_id: 5 },
  { date: '2025-02-26', user_id: 1 },
  { date: '2025-02-27', user_id: 2 },
  { date: '2025-02-28', user_id: 3 },
  { date: '2025-03-01', user_id: 4 },
  { date: '2025-03-02', user_id: 5 },
];


export const mealPlanRecipes = [
  { plan_id: 1, recipe_id: 1, total_servings: 4, meal_type: 'Dinner' },
  { plan_id: 2, recipe_id: 2, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 3, recipe_id: 3, total_servings: 2, meal_type: 'Dinner' },
  { plan_id: 4, recipe_id: 4, total_servings: 5, meal_type: 'Breakfast' },
  { plan_id: 5, recipe_id: 5, total_servings: 6, meal_type: 'Lunch' },
  { plan_id: 6, recipe_id: 6, total_servings: 4, meal_type: 'Dinner' },
  { plan_id: 7, recipe_id: 7, total_servings: 3, meal_type: 'Dinner' },
  { plan_id: 8, recipe_id: 8, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 9, recipe_id: 9, total_servings: 5, meal_type: 'Breakfast' },
  { plan_id: 10, recipe_id: 10, total_servings: 2, meal_type: 'Lunch' },
  { plan_id: 11, recipe_id: 11, total_servings: 6, meal_type: 'Dinner' },
  { plan_id: 12, recipe_id: 12, total_servings: 3, meal_type: 'Dinner' },
  { plan_id: 13, recipe_id: 13, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 14, recipe_id: 14, total_servings: 5, meal_type: 'Dinner' },
  { plan_id: 15, recipe_id: 15, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 16, recipe_id: 16, total_servings: 3, meal_type: 'Dinner' },
  { plan_id: 17, recipe_id: 17, total_servings: 2, meal_type: 'Dinner' },
  { plan_id: 18, recipe_id: 18, total_servings: 6, meal_type: 'Breakfast' },
  { plan_id: 19, recipe_id: 19, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 20, recipe_id: 20, total_servings: 5, meal_type: 'Dinner' },
  { plan_id: 21, recipe_id: 21, total_servings: 4, meal_type: 'Dinner' },
  { plan_id: 22, recipe_id: 22, total_servings: 3, meal_type: 'Breakfast' },
  { plan_id: 23, recipe_id: 23, total_servings: 2, meal_type: 'Lunch' },
  { plan_id: 24, recipe_id: 24, total_servings: 6, meal_type: 'Dinner' },
  { plan_id: 25, recipe_id: 25, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 26, recipe_id: 26, total_servings: 3, meal_type: 'Dinner' },
  { plan_id: 27, recipe_id: 27, total_servings: 2, meal_type: 'Dinner' },
  { plan_id: 28, recipe_id: 28, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 29, recipe_id: 29, total_servings: 5, meal_type: 'Dinner' },
  { plan_id: 30, recipe_id: 30, total_servings: 3, meal_type: 'Lunch' },
  { plan_id: 31, recipe_id: 31, total_servings: 6, meal_type: 'Dinner' },
  { plan_id: 32, recipe_id: 32, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 33, recipe_id: 33, total_servings: 5, meal_type: 'Dinner' },
  { plan_id: 34, recipe_id: 34, total_servings: 3, meal_type: 'Breakfast' },
  { plan_id: 35, recipe_id: 35, total_servings: 6, meal_type: 'Dinner' },
  { plan_id: 36, recipe_id: 36, total_servings: 4, meal_type: 'Lunch' },
  { plan_id: 37, recipe_id: 37, total_servings: 2, meal_type: 'Dinner' },
  { plan_id: 38, recipe_id: 38, total_servings: 6, meal_type: 'Breakfast' },
  { plan_id: 39, recipe_id: 39, total_servings: 5, meal_type: 'Dinner' },
  { plan_id: 40, recipe_id: 40, total_servings: 4, meal_type: 'Lunch' },
];


export const shoppingLists = [
  { plan_id: 1 },
  { plan_id: 2 },
  { plan_id: 3 },
  { plan_id: 4 },
  { plan_id: 5 },
  { plan_id: 6 },
  { plan_id: 7 },
  { plan_id: 8 },
  { plan_id: 9 },
  { plan_id: 10 },
  { plan_id: 11 },
  { plan_id: 12 },
  { plan_id: 13 },
  { plan_id: 14 },
  { plan_id: 15 },
  { plan_id: 16 },
  { plan_id: 17 },
  { plan_id: 18 },
  { plan_id: 19 },
  { plan_id: 20 },
  { plan_id: 21 },
  { plan_id: 22 },
  { plan_id: 23 },
  { plan_id: 24 },
  { plan_id: 25 },
  { plan_id: 26 },
  { plan_id: 27 },
  { plan_id: 28 },
  { plan_id: 29 },
  { plan_id: 30 },
  { plan_id: 31 },
  { plan_id: 32 },
  { plan_id: 33 },
  { plan_id: 34 },
  { plan_id: 35 },
  { plan_id: 36 },
  { plan_id: 37 },
  { plan_id: 38 },
  { plan_id: 39 },
  { plan_id: 40 },
];


export const shoppingListItems = [
  { list_id: 1, ingredient_id: 1, quantity: 2, unit: 'Tomatoes' },
  { list_id: 2, ingredient_id: 2, quantity: 3, unit: 'Garlic cloves' },
  { list_id: 3, ingredient_id: 3, quantity: 1, unit: 'Olive Oil tablespoon' },
  { list_id: 4, ingredient_id: 4, quantity: 2, unit: 'Lemon' },
  { list_id: 5, ingredient_id: 5, quantity: 1, unit: 'Cucumber' },
  { list_id: 6, ingredient_id: 6, quantity: 1, unit: 'Red Onion' },
  { list_id: 7, ingredient_id: 7, quantity: 4, unit: 'Eggs' },
  { list_id: 8, ingredient_id: 8, quantity: 2, unit: 'Bell Pepper' },
  { list_id: 9, ingredient_id: 9, quantity: 3, unit: 'Carrots' },
  { list_id: 10, ingredient_id: 10, quantity: 1, unit: 'Potato' },
  { list_id: 11, ingredient_id: 11, quantity: 1, unit: 'Chicken Breast' },
  { list_id: 12, ingredient_id: 12, quantity: 2, unit: 'Avocados' },
  { list_id: 13, ingredient_id: 13, quantity: 5, unit: 'Tomato' },
  { list_id: 14, ingredient_id: 14, quantity: 3, unit: 'Garlic clove' },
  { list_id: 15, ingredient_id: 15, quantity: 2, unit: 'Red Onion' },
  { list_id: 16, ingredient_id: 16, quantity: 2, unit: 'Bell Pepper' },
  { list_id: 17, ingredient_id: 17, quantity: 1, unit: 'Lettuce head' },
  { list_id: 18, ingredient_id: 18, quantity: 4, unit: 'Eggs' },
  { list_id: 19, ingredient_id: 19, quantity: 2, unit: 'Carrots' },
  { list_id: 20, ingredient_id: 20, quantity: 1, unit: 'Chicken Breast' },
  { list_id: 21, ingredient_id: 21, quantity: 1, unit: 'Spinach' },
  { list_id: 22, ingredient_id: 22, quantity: 1, unit: 'Sweet Potato' },
  { list_id: 23, ingredient_id: 23, quantity: 1, unit: 'Cucumber' },
  { list_id: 24, ingredient_id: 24, quantity: 1, unit: 'Feta Cheese' },
  { list_id: 25, ingredient_id: 25, quantity: 2, unit: 'Zucchini' },
  { list_id: 26, ingredient_id: 26, quantity: 1, unit: 'Bacon strip' },
  { list_id: 27, ingredient_id: 27, quantity: 2, unit: 'Chicken Legs' },
  { list_id: 28, ingredient_id: 28, quantity: 3, unit: 'Tomatoes' },
  { list_id: 29, ingredient_id: 29, quantity: 1, unit: 'Olive Oil' },
  { list_id: 30, ingredient_id: 30, quantity: 2, unit: 'Bell Pepper' },
  { list_id: 31, ingredient_id: 31, quantity: 2, unit: 'Lettuce' },
  { list_id: 32, ingredient_id: 32, quantity: 3, unit: 'Carrots' },
  { list_id: 33, ingredient_id: 33, quantity: 4, unit: 'Garlic clove' },
  { list_id: 34, ingredient_id: 34, quantity: 1, unit: 'Spinach' },
  { list_id: 35, ingredient_id: 35, quantity: 2, unit: 'Eggs' },
  { list_id: 36, ingredient_id: 36, quantity: 1, unit: 'Sweet Potato' },
  { list_id: 37, ingredient_id: 37, quantity: 2, unit: 'Red Onion' },
  { list_id: 38, ingredient_id: 38, quantity: 1, unit: 'Avocado' },
  { list_id: 39, ingredient_id: 39, quantity: 1, unit: 'Cucumber' },
  { list_id: 40, ingredient_id: 40, quantity: 3, unit: 'Tomatoes' },
];
